name: Deploy
on:
  workflow_run:
  workflows: ["Test"]
  types:
    - completed
    - success

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Change directory
        run: cd ./
      - name: Deploy
        run: echo "Deploying to production..."
