name: CI/CD Workflow
on:
  push:
    branches:
      - main

jobs:
  # Installation
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Clear npm cache
        run: npm cache clean --force
        working-directory: ${{ github.workspace }}
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install dependencies
        run: npm install
        working-directory: ${{ github.workspace }}

  # Tests
  test:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Verify directory
        run: ls -alh ${{ github.workspace }}  # List files in the directory
      - name: Test
        run: npm run test
        working-directory: ${{ github.workspace }}

  # Build
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Build
        run: npm run build
        working-directory: ${{ github.workspace }}

  # Deploy
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy
        run: echo "Deploying to production..."
        working-directory: ${{ github.workspace }}
