name: Send Discord
on:
  workflow_run:
  workflows: ["Deploy"]
  types:
    - completed
    - success

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d '{"content": "Le deploy est terminé ! (je suis trop fort)"}' \
            ${{ secrets.DISCORD_WEBHOOK_URL }}
